# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_channels', '0015_pushsubscriptioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='display_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_verb',
            field=models.CharField(max_length=255),
        ),
    ]
